name: foods_store_app
description: A new Flutter application.



publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/lianyagang/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2  # flutter_swiper很久不维护，可以使用空安全版本：flutter_swiper_null_safety
  # 启动URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.6
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.8.0+3
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.0.9
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.0.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0

  device_info: ^2.0.2
  # 获取软件版本信息 https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.2
  # Json转Model https://pub.flutter-io.cn/packages/json_serializable
  json_annotation: ^4.0.1
  # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^1.0.1
  # https://pub.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.0
  # 屏幕适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0+2
  # 刷新框架 https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.1
  # 弹框 https://pub.flutter-io.cn/packages/flutter_picker
  flutter_picker: ^2.0.2
  convex_bottom_bar: ^3.0.0
  #动态加载条加载页面
  shimmer: ^2.0.0
  gzx_dropdown_menu: ^3.1.0
  path_drawing: ^0.5.1
  open_file: ^3.2.1
  sign_in_with_apple: ^3.0.0
  http: ^0.13.3
  meta: ^1.3.0
  uuid: ^3.0.4
  bot_toast: 4.0.1
  scrollable_list_tabview: ^0.2.0-nullsafety
dev_dependencies:

  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  # flutter_driver:
  #   sdk: flutter
  # integration_test:
  #   sdk: flutter
  # 黄金测试
  #  flutter_goldens:
  #    sdk: flutter
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  # 单元测试
  test: ^1.16.8
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/images/login/
    - assets/images/me/
    - assets/images/dashboard/
    - assets/images/state/
    - assets/images/personnel/
    - assets/images/product/
    - assets/images/company/
    - assets/images/search/
  fonts:
    - family: iconfontFonts
      fonts:
        - asset: assets/fonts/Iconfont.ttf
